#!/bin/sh

#SBATCH --job-name=ds001748-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001748-fmriprep/.reproman/jobs/local/20220807-143006-0488/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001748-fmriprep/.reproman/jobs/local/20220807-143006-0488/stderr

#SBATCH --nodes=16
#SBATCH --ntasks=62
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001748-fmriprep/.reproman/jobs/local/20220807-143006-0488

module load launcher
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 61); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

"$LAUNCHER_DIR"/paramrun